### ISSUE TITLE
import forallpeople as si loads units to global builtins, not to si as expected from the docs

### ISSUE THREAD

**Issue by lukasreimer** [connorferster/forallpeople#8]
I have noticed that on version 1.3.1, the import and usage strategy proposed in the readme does not work as expected or is broken. The units end up living in the global namespace regardless of the import statement. See the ipython session below:

```python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import forallpeople as si

In [2]: si.m
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0b9dacaea368> in <module>
----> 1 si.m

AttributeError: module 'forallpeople' has no attribute 'm'

In [3]: m
Out[3]: 1.000 m

In [4]: dir(__builtins__)
Out[4]:
['A',
 'ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
# rest omitted


In [5]: si.__version__
Out[5]: '1.3.1'
```

Is this a bug or supposed to be a feature. I would rather like to be able to choose between the option of importing the units (Physical instances) to the global namespace or preferrably using a separate namespace like demonstrated in the docs.

**Comment by connorferster** [comment]
Hi Lukas,

Thanks for bringing this up. Yes, it's intended to be a feature. I am planning on updating the docs imminently. 

It's something that I have been battling with. The following has been my thinking on this to date:

* I use the units everyday in my work and, generally, the workflow that I have preferred is to have the units populate into the top-level namespace. This is so that the appearance of the code perhaps looks more "intuitive". However, it is a good Python convention (and a convention I prefer) to separate objects into separate namespaces so that when people read the code, it's clear where everything came from.
* The basic design concept of `forallpeople` is that the units exist "at one's fingertips", i.e not a part of a container or registry. They can exist independently of their definitions since they are vector-based objects and have meaning as such regardless of how they are represented through whichever representative environment (i.e. a kg*m*s**-2 quantity is exists independently of whether it is called a Newton or a pound). 
* With the version that existed when the docs were written, every time a new environment was loaded it would populate the module namespace without removing the previous unit variables. It would also require an awkward "re-import" of the module, which seemed kind of a "hack-y" to me. I especially felt this when doing a double `from forallpeople import *` import to get variables into the top-level namespace.
* I still wanted the ability to "push" variables into the top level namespace as environments are loaded and so the solution I found is by dynamically adding unit variables to `builtins`. By pushing to builtins, I have the capability of removing them from the namespace when the environment changes, thereby preventing excessive pollution of the top-level namespace every time a new environment is loaded. I have not been successful in performing this in the module namespace to date but maybe it has been because there is something I do not know yet.
* However, as I am typing all of this, I am realizing that I am perhaps being a bit silly. The "globals" and "builtins" are also just containers, albeit privileged by having its members be accessible in the top-level namespace. So, if I let go of some of the assumptions I had at the beginning of this project, it should be quite possible to set up a separate container for the units that can be accessed through a separate namespace. 

I will look into it. I think I can come up with a more robust solution at this point. 

Would you be able to tell me a bit more of how you would like to use the library? What are the elements of it that have attracted you to it so far in place of other unit libraries? Currently, it `forallpeople` feels like something I use alone. I would love to hear your feedback!

**Comment by connorferster** [comment]
In progress...

**Comment by connorferster** [comment]
The problem has been fixed in the recently published v2.0.0

Updates to documentation pending...

As follows:

```python
import forallpeople as si
si.environment('default') # This will push unit variables defined in the 'default' environment into the module namespace
si.environment('default', top_level = True) # This will push unit variables into the top level namespace (via builtins)
```

**Comment by lukasreimer** [comment]
Hi Connor,

I am a mechanical engineer and I indend to use this for some quick calculations. So I picked up your library and wasn't quite sure how best to use it. And I am also still not 100% sure in light of the many different possibilities (like REPL sessions, notebooks, etc.). My feeling was it should be either optional there should only be one single (documented) way. Thanks for looking into this so quickly. I think it is a very clean solution to allow both options. I am looking forward to using your package more often now.

The element that interested me the most in your units package is the way it handles dimensionless values just as bare numbers. This is very neat and really stands out to me in comparison my (little) experience with other such packages (namely pint).

**Comment by connorferster** [comment]
Yes! My belief was that dimensioned units should be able to cancel each other out, leaving just a number. I do not think it makes sense to have a dimensionless unit for rads. By cancelling out, trigonometric functions can easily be used with the units in an intuitive way, e.g. `tan(4*m / 3*m)` without any special workarounds. 

Additionally, I find that many engineering code calculations are "empirical" formulae that are not dimensionally consistent. This is especially true in concrete design codes where it is established that the result of the square root of a pressure in Pascals is also in Pascals. When you apply the `math.sqrt(...)` function to a Physical instance, `math.sqrt(...)` will first convert the object to a float. Physical instances convert to floats gracefully so that `float(35*MPa)` will return `35` instead of `35000000`, which would be the its base value in SI units. So a code formula of `sqrt(35*MPa)` will return the sqrt of 35 as `5.92`, which is what the formula is attempting to achieve. This calculation can be performed, with units maintained, just by `sqrt(35*MPa) * MPa` to return `5.92 MPa`.

Have you looked at my handcalcs library yet? While forallpeople was created first, before handcalcs was even a fully formed idea, they were designed to be used together in Jupyter Notebook/Lab for an intuitive workflow. 

https://github.com/connorferster/handcalcs

Additionally, I will be updating the documentation for `forallpeople` over the next week. Hopefully, all the ways of using it will become much clearer.

**Comment by lukasreimer** [comment]
Thanks for the in-depth explanation. I am not familiar with any concrete design codes but I know similar cases from my field.
I have seen `handcalcs`, but not yet used it. It seems to make sense to use them together right away. Even without `handcalcs` the code using `forallpeople` already looks very close to what you would write by hand. Great stuff!
